/** @jest-environment jsdom */

import { PdfPreviewModal } from '../src/report/PdfPreviewModal'

const renderPage = jest.fn(() => ({
  promise: Promise.resolve(),
  cancel: jest.fn()
}))

jest.mock('pdfjs-dist', () => ({
  GlobalWorkerOptions: { workerSrc: '' },
  getDocument: () => ({
    promise: Promise.resolve({
      numPages: 2,
      destroy: jest.fn(),
      getPage: jest.fn(async () => ({
        getViewport: ({ scale }: { scale: number }) => ({
          width: 100 * scale,
          height: 140 * scale
        }),
        render: renderPage
      }))
    })
  })
}))

describe('PdfPreviewModal', () => {
  beforeEach(() => {
    document.body.replaceChildren()
    Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
      configurable: true,
      value: jest.fn(() => ({}))
    })
  })

  afterEach(() => {
    document.body.classList.remove('pdf-preview-open')
    jest.restoreAllMocks()
  })

  it('renders generated bytes with navigation, zoom, fit, and download controls', async () => {
    const createObjectUrl = jest.fn(() => 'blob:preview')
    const revokeObjectUrl = jest.fn()
    Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: createObjectUrl })
    Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: revokeObjectUrl })
    const anchorClick = jest.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation()
    const modal = new PdfPreviewModal(() => 'zh')

    await modal.open('report.pdf', new Uint8Array([1, 2, 3]))

    expect(document.querySelector('#pdfPreviewTitle')?.textContent).toBe('report.pdf')
    expect(document.querySelector('[aria-label="上一页"]')).not.toBeNull()
    expect(document.querySelector('[aria-label="下一页"]')).not.toBeNull()
    expect(document.querySelector('[aria-label="放大"]')).not.toBeNull()
    expect(document.querySelector('[aria-label="适合宽度"]')).not.toBeNull()
    document.querySelector<HTMLButtonElement>('[aria-label="下一页"]')?.click()
    await Promise.resolve()
    expect(document.querySelector<HTMLInputElement>('[aria-label="PDF 页码"]')?.value).toBe('2')

    document.querySelector<HTMLButtonElement>('[aria-label="下载 PDF"]')?.click()
    expect(createObjectUrl).toHaveBeenCalledTimes(1)
    expect(anchorClick).toHaveBeenCalledTimes(1)
  })
})