import { chromium } from '../../node_modules/.pnpm/playwright@1.59.1/node_modules/playwright/index.mjs'
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

const output = fileURLToPath(new URL('./', import.meta.url))
await mkdir(`${output}/original`, { recursive: true })
const browser = await chromium.launch({ channel: 'msedge', headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, locale: 'zh-CN' })
  const manifest = []
  const capture = async (name, targets = []) => {
    const boxes = []
    for (const [label, selector] of targets) {
      const locator = page.locator(selector).first()
      await locator.waitFor({ state: 'visible', timeout: 5000 }).catch(() => {})
      if (await locator.isVisible()) {
        const box = await locator.boundingBox()
        if (box) boxes.push({ label, ...box })
      }
    }
    await page.screenshot({ path: `${output}/original/${name}.png` })
    const text = await page.locator('body').innerText()
    const controls = await page.locator('[role="dialog"]:visible button, [role="dialog"]:visible input, [role="dialog"]:visible select').evaluateAll(elements => elements.map(element => ({ tag: element.tagName, text: element.textContent?.trim().slice(0, 100), label: element.getAttribute('aria-label'), class: element.className })))
    manifest.push({ name, boxes, text, controls })
    console.log(`${name}: ${boxes.length} annotation targets`)
    await writeFile(`${output}/manifest.json`, JSON.stringify(manifest, null, 2))
  }
  await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
  await capture('00-login', [['用户名', 'input[autocomplete="username"]'], ['密码', 'input[type="password"]'], ['登录', 'button[type="submit"]']])
  await page.locator('input[autocomplete="username"]').fill('manual-demo')
  await page.locator('input[type="password"]').fill('manual-demo')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.locator('.login-view').waitFor({ state: 'hidden' }).catch(() => {})
  await page.locator('#pidDrawingLibraryButton').waitFor({ state: 'visible' })
  await page.locator('#phaseContextPhase option').first().waitFor({ state: 'attached' })
  await page.waitForLoadState('networkidle')
  await capture('01-workspace', [['图纸库', '#pidDrawingLibraryButton'], ['项目管理', '#projectManagementButton'], ['报告', '#reportWorkspaceButton']])
  await page.locator('#projectManagementButton').click()
  await page.locator('.project-management-modal').waitFor({ state: 'visible' })
  await page.locator('.project-list-item').first().waitFor({ state: 'visible' })
  await page.waitForLoadState('networkidle')
  await capture('02-projects', [['项目列表', '.project-list'], ['新建项目', '[aria-label="新建 Project"]']])
  await page.getByRole('button', { name: '新建 Project', exact: true }).click()
  await capture('03-project-create', [['基本信息', '.project-editor-panel input'], ['选择图纸', '.project-drawing-list'], ['创建', '.project-primary-button']])
  await page.getByRole('button', { name: '关闭 Project 管理', exact: true }).click()
  await page.locator('#pidDrawingLibraryButton').click()
  await page.locator('.drawing-library-modal').waitFor({ state: 'visible' })
  await page.locator('.drawing-upload-panel').waitFor({ state: 'visible' })
  await page.waitForLoadState('networkidle')
  await capture('04-library', [['图纸名称', '.drawing-upload-panel input[type="text"]'], ['选择文件', '.drawing-upload-file'], ['上传', '.drawing-library-primary-button']])
  await capture('18-library-search', [['搜索', '.drawing-library-modal input[type="search"]'], ['查看图纸', '[aria-label="查看图纸"]'], ['解析摘要', '[aria-label="查看解析摘要"]']])
  const summary = page.getByRole('button', { name: '查看解析摘要', exact: true }).first()
  if (await summary.isVisible()) {
    await summary.click()
    await page.waitForLoadState('networkidle')
    await capture('05-parsing', [['解析摘要', '[aria-labelledby="drawingParseDetailsTitle"]']])
    await page.getByRole('button', { name: '关闭解析详情', exact: true }).click()
  }
  await page.getByRole('button', { name: '关闭图纸库', exact: true }).click()
  await capture('06-phase', [['工艺选择', '[aria-label="当前工艺"]'], ['新增序列', '[aria-label="新增序列"]'], ['创建阶段', 'button:has-text("创建 Phase")']])
  await page.getByRole('button', { name: '新增序列', exact: true }).click()
  await capture('15-sequence', [['序列编号', '[aria-label="序列编号"]'], ['序列名称', '[aria-label="序列名称"]'], ['创建', '[role="dialog"]:visible .phase-workspace-primary']])
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '创建 Phase', exact: true }).click()
  await capture('07-phase-create', [['编号', '[aria-label="阶段编号"]'], ['名称', '[aria-label="阶段名称"]'], ['创建方式', '[aria-label="阶段创建方式"]']])
  await page.getByRole('button', { name: '关闭创建 Phase 对话框', exact: true }).click()
  await page.getByRole('button', { name: '更换图纸', exact: true }).click()
  await capture('08-phase-drawing', [['来源', '[aria-label="图纸关联方式"]'], ['图纸', '[aria-label="请选择 Project PID"]'], ['确认', 'button:has-text("确认更换")']])
  await page.getByRole('button', { name: '关闭关联图纸对话框', exact: true }).click()
  await page.locator('#phaseConfigImport').click()
  await capture('09-import', [['选择 Excel', '.phase-config-import-dropzone'], ['导入确认', '.phase-config-import-confirm']])
  await page.locator('.phase-config-import-close').click()
  await page.locator('#phaseHighlightStyleButton').click()
  await capture('10-styles', [['设备名称', '[aria-label="设备名称"]'], ['状态名称', '[aria-label="右键显示名称"]'], ['流路行为', '[role="dialog"]:visible select']])
  await page.locator('.highlight-style-modal').getByRole('button', { name: '取消', exact: true }).click()
  await page.locator('#reportWorkspaceButton').click()
  await page.locator('.report-workspace-modal').waitFor({ state: 'visible' })
  await capture('11-report', [['页面列表', '.report-page-browser'], ['页面属性', '.report-page-inspector'], ['导出设置', '.report-pdf-tabs']])
  const settings = page.getByRole('tab', { name: '页面设置&导出', exact: true })
  if (await settings.isVisible()) await settings.click()
  await capture('12-pdf-settings', [['文件名', '[aria-label="自定义 PDF 文件名"]'], ['合并 PDF', 'button:has-text("合并为一个 PDF")'], ['分序列 ZIP', 'button:has-text("每个序列一个 PDF")']])
  await page.locator('#matrixExportTab').click()
  await capture('13-matrix', [['范围', '.report-matrix-workspace select'], ['文件名', '[aria-label="自定义 Matrix 文件名"]'], ['导出', '.report-matrix-workspace button.report-primary-button']])
  await page.getByRole('button', { name: '关闭报告工作区', exact: true }).click()
  await capture('14-save', [['阶段切换', '#phaseContextPhase'], ['保存', '#phaseContextSave'], ['高亮样式', '#phaseHighlightStyleButton']])
  await capture('16-tank', [['筛选 Tank', '[aria-label="当前 Tank"]'], ['定位 Tank', '[aria-label="定位 Tank"]'], ['阶段归属', '[aria-label="Phase 所属 Tank"]']])
  await page.getByRole('button', { name: '复制 Phase', exact: true }).first().click()
  await capture('17-phase-copy', [['目标序列', '[aria-label="目标序列"]'], ['编号', '[aria-label="新 Phase 编号"]'], ['名称', '[aria-label="新 Phase 名称"]']])
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await capture('19-tools', [['缩放至范围', '[aria-label="缩放至范围"]'], ['画笔', '[aria-label="画笔"]'], ['擦除', '[aria-label="擦除"]']])
  await page.getByRole('button', { name: '画笔', exact: true }).click()
  await capture('20-brush', [['样式来源', '[aria-label="样式来源"]'], ['颜色', '[aria-label="自定义十六进制颜色"]'], ['应用', '[role="dialog"]:visible button:has-text("应用")']])
  await page.getByRole('button', { name: '关闭样式选择对话框', exact: true }).click()
  const controls = await page.locator('button:visible,input:visible,select:visible,a:visible').evaluateAll(elements => elements.map(element => ({
    tag: element.tagName, id: element.id, text: element.textContent?.trim().slice(0, 100),
    title: element.getAttribute('title'), label: element.getAttribute('aria-label'), type: element.getAttribute('type')
  })))
  await writeFile(`${output}/inspection.json`, JSON.stringify({ text: await page.locator('body').innerText(), controls }, null, 2))
  console.log(`Captured ${manifest.length} screens`)
} finally {
  await browser.close()
}